Provisioner:
  create: true
  consolidation:
    enabled: true
# Don't use these values when consolidation is enabled
  # ttlSecondsAfterEmpty: 300
  # ttlSecondsUntilExpired: 86400 
  provider:          # Mention the AWSNodeTemplate name here
    name: default
  requirements:
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["c"]
    # - key: "karpenter.k8s.aws/instance-cpu"
    #   operator: In
    #   values: ["4", "8", "16", "32"]
    # - key: "karpenter.k8s.aws/instance-hypervisor"
    #   operator: In
    #   values: ["nitro"]
    # - key: karpenter.k8s.aws/instance-generation
    #   operator: Gt
    #   values: ["2"]
    # - key: "topology.kubernetes.io/zone"
    #   operator: In
    #   values: ["us-west-2a", "us-west-2b"]
    # - key: "kubernetes.io/arch"
    #   operator: In
    #   values: ["arm64", "amd64"]
    - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["spot", "on-demand"]
  taints:
    # - key: example.com/special-taint
    #   effect: NoSchedule
  labels:
    created_by: karpenter
  # Resource limits constrain the total size of the cluster.
  # Limits prevent Karpenter from creating new instances once the limit is exceeded.
  clusterConstraints:
    create: false
    limits:
      resources:
        cpu: "1000"
        memory: "1000Gi"