tcp:
  27017: mongodb/mongodb-server:27017
  # 27018: mongo-haifa/mongo-public:27017
  # 5432: timescaledb/timescaledb:5432
  # 9202: boundary-worker/boundary-0:9202
controller:
  config:
      http-snippet: |
         server {
            listen 2443;
            return 308 https://$host$request_uri;
          }
      use-forwarded-headers: 'false'
  containerPort: {"http":80,"https":443, "tohttps": 2443}
  service:
    targetPorts:
      http: tohttps
      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:058264118225:certificate/eb435125-2ad6-4042-8cd1-bc3660ce25a1
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-target-node-labels: created_by=karpenter
  nodeSelector:
    eks.amazonaws.com/nodegroup: rocketbuilds-managed-ng-01
